require 'rexml/document'
require 'json'

kml_file = File.join(File.dirname(__FILE__), 'data', 'doc.kml')
json_file = File.join(File.dirname(__FILE__), 'data', 'kmls.json')
dest_dir = File.join(File.dirname(__FILE__), 'data', 'kmls')

kml_data = {}

puts "loading #{kml_file}"
kml_doc = REXML::Document.new File.new kml_file

SIMPLE_KML = <<-KML
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Feature Manipulation Engine 2010 SP3 (Build 6231) -->
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:gx="http://www.google.com/kml/ext/2.2">
  <Document>
    <Placemark>
    </Placemark>
  </Document>
</kml>
KML

puts "starting parse"
kml_doc.elements.each("kml/Document/Folder/Folder/Placemark") do |community_folder|

  community_name = community_folder.elements["ExtendedData/SchemaData/SimpleData[@name='NAME']"].text
  puts "community_name = #{community_name}"

  community_code = community_folder.elements["ExtendedData/SchemaData/SimpleData[@name='COMM_CODE']"].text
  kml_data[community_name] = community_code

  polygon = community_folder.elements["Polygon"]

  output_kml = REXML::Document.new SIMPLE_KML
  placemark = output_kml.elements["kml/Document/Placemark"]
  placemark.add_element polygon

  File.open(File.join(dest_dir, "#{community_code}.kml"), 'w') do |file|
    output_kml.write file, 1
  end
end

File.open(json_file, 'w') do |file|
  file.write(JSON.pretty_generate(kml_data))
end

